# Generated by Django 3.1.4 on 2021-03-03 09:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Marks',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('roll_no', models.CharField(max_length=100)),
                ('name', models.CharField(max_length=150)),
                ('math_marks', models.IntegerField(default=0)),
                ('physics_marks', models.IntegerField(default=0)),
                ('chemistry_marks', models.IntegerField(default=0)),
            ],
            options={
                'verbose_name_plural': 'Marks',
            },
        ),
    ]
