# Generated by Django 3.1.4 on 2021-03-03 12:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='marks',
            name='percentage',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='marks',
            name='total',
            field=models.IntegerField(default=0),
        ),
    ]
